// 用户登录
export const LOGIN = 'LOGIN';
export const GET_AUTHORITIES = 'GET_AUTHORITIES';

// 面包屑
export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';

// 权限控制
export const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
export const SET_USERINFO = 'SET_USERINFO';
export const SET_TOKEN = 'SET_TOKEN';
export const CLERN_TOKEN = 'CLERN_TOKEN';
export const CLERN_USERINFO = 'CLERN_USERINFO';
export const SET_AUTHORITIES = 'SET_AUTHORITIES';

// 代办员列表
export const SET_AGENT_LIST = 'SET_AGENT_LIST';
export const SET_AGENT_DETAIL = 'SET_AGENT_DETAIL';

// 地区
export const SET_REGION_LIST = 'SET_REGION_LIST';

// 商品和类别
export const SET_GOODSCATEGORY_LIST = 'SET_GOODSCATEGORY_LIST';
export const SET_GOODSCATEGORY_DETAIL = 'SET_GOODSCATEGORY_DETAIL';
export const SET_GOODS_LIST = 'SET_GOODS_LIST';
export const SET_GOODS_DETAIL = 'SET_GOODS_DETAIL';
export const SET_GOODSUNIT_LIST = 'SET_GOODSUNIT_LIST';

// 导出
// 采购单
export const SET_PURCHASE_KEY = 'SET_PURCHASE_KEY';
export const SET_PURCHASE_DETAIL_KEY = 'SET_PURCHASE_DETAIL_KEY';
export const SET_ENTRY_KEY = 'SET_ENTRY_KEY';
export const SET_ENTRY_DETAIL_KEY = 'SET_ENTRY_DETAIL_KEY';
export const SET_PROCESS_KEY = 'SET_PROCESS_KEY';
export const SET_PROCESS_DETAIL_KEY = 'SET_PROCESS_DETAIL_KEY';

export const SET_DELIVERY_KEY = 'SET_DELIVERY_KEY';
export const SET_DELIVERY_DETAIL_KEY = 'SET_DELIVERY_DETAIL_KEY';
export const SET_RECORD_KEY = 'SET_RECORD_KEY';
export const SET_SALE_REPORT_KEY = 'SET_SALE_REPORT_KEY';
export const SET_SALE_ORDER_KEY = 'SET_SALE_ORDER_KEY';
export const SET_SALE_ORDER_DETAIL_KEY = 'SET_SALE_ORDER_DETAIL_KEY';

// 采购单管理
export const SET_PURCHASE_LIST = 'SET_PURCHASE_LIST';
export const SET_PURCHASE_DETAIL = 'SET_PURCHASE_DETAIL';

// 入库单管理
export const SET_ENTRY_LIST = 'SET_ENTRY_LIST';
export const SET_ENTRY_DETAIL = 'SET_ENTRY_DETAIL';

// 加工单管理
export const SET_PROCESSING_LIST = 'SET_PROCESSING_LIST';
export const SET_PROCESSING_DETAIL = 'SET_PROCESSING_DETAIL';

// 发货单管理
export const SET_DELIVERY_LIST = 'SET_DELIVERY_LIST';
export const SET_DELIVERY_DETAIL = 'SET_DELIVERY_DETAIL';

// 销售记录
export const SET_RECORD_LIST = 'SET_RECORD_LIST';
// 商品销售报表
export const SET_SALE_REPORT_LIST = 'SET_SALE_REPORT_LIST';

export const SET_SALE_ORDER_LIST = 'SET_SALE_ORDER_LIST';
export const SET_SALE_ORDER_DETAIL = 'SET_SALE_ORDER_DETAIL';
// 销售市场
export const SET_MARKET_LIST = 'SET_MARKET_LIST';
export const SET_MARKET_DETAIL = 'SET_MARKET_DETAIL';

// 用户
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const SET_USERS_DETAIL = 'SET_USERS_DETAIL';

// app-upload
export const SET_APP_UPLOAD_LIST = 'SET_APP_UPLOAD_LIST';

// 采购入库单
export const SET_WAREHOUSE_INVOICE_LIST = 'SET_WAREHOUSE_INVOICE_LIST';
export const SET_WAREHOUSE_INVOICE_DETAIL = 'SET_WAREHOUSE_INVOICE_DETAIL';
export const SET_WAREHOUSE_INVOICE_SUB_DETAIL = 'SET_WAREHOUSE_INVOICE_SUB_DETAIL';

// 调拨单
export const SET_TRANSFER_INVOICE_LIST = 'SET_TRANSFER_INVOICE_LIST';
export const SET_TRANSFER_INVOICE_DETAIL = 'SET_TRANSFER_INVOICE_DETAIL';
export const SET_TRANSFER_INVOICE_SUB_DETAIL = 'SET_TRANSFER_INVOICE_SUB_DETAIL';

// 销售出库单
export const SET_SALEOUT_INVOICE_LIST = 'SET_SALEOUT_INVOICE_LIST';
export const SET_SALEOUT_INVOICE_DETAIL = 'SET_SALEOUT_INVOICE_DETAIL';
export const SET_SALEOUT_INVOICE_SUB_DETAIL = 'SET_SALEOUT_INVOICE_SUB_DETAIL';

// 损益单
export const SET_ADJUSTMENT_INVOICE_LIST = 'SET_ADJUSTMENT_INVOICE_LIST';
export const SET_ADJUSTMENT_INVOICE_DETAIL = 'SET_ADJUSTMENT_INVOICE_DETAIL';

// 设置菜单栏
export const SET_DEFAULT_ACTIVE = 'SET_DEFAULT_ACTIVE';





// 商户列表
export const SET_MERCHANTS_LIST = 'SET_MERCHANTS_LIST';
export const SET_MERCHANTS_DETAIL = 'SET_MERCHANTS_DETAIL';